/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./components/ActionsMenu.vue')['default']
    Bag: typeof import('./components/Bag.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    CollectionEntries: typeof import('./components/CollectionEntries.vue')['default']
    CollectionEntry: typeof import('./components/CollectionEntry.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    CustomSelect: typeof import('./components/CustomSelect.vue')['default']
    DarkSwitcher: typeof import('./components/DarkSwitcher.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    DrawerClose: typeof import('./components/ui/drawer/DrawerClose.vue')['default']
    DrawerContent: typeof import('./components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./components/ui/drawer/DrawerTitle.vue')['default']
    DrawerTrigger: typeof import('./components/ui/drawer/DrawerTrigger.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    FAB: typeof import('./components/FAB.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelpPage: typeof import('./components/HelpPage.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    IconCanvas: typeof import('./components/IconCanvas.vue')['default']
    IconCard: typeof import('./components/IconCard.vue')['default']
    IconDetail: typeof import('./components/IconDetail.vue')['default']
    IconGrid: typeof import('./components/IconGrid.vue')['default']
    Icons: typeof import('./components/Icons.vue')['default']
    IconSet: typeof import('./components/IconSet.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    InstallIconSet: typeof import('./components/InstallIconSet.vue')['default']
    MainSearch: typeof import('./components/MainSearch.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalDialog: typeof import('./components/ModalDialog.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavElectron: typeof import('./components/electron/NavElectron.vue')['default']
    NavPlaceholder: typeof import('./components/electron/NavPlaceholder.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Progress: typeof import('./components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SearchElectron: typeof import('./components/electron/SearchElectron.vue')['default']
    SearchHeader: typeof import('./components/SearchHeader.vue')['default']
    SettingsCollectionsList: typeof import('./components/SettingsCollectionsList.vue')['default']
    Slider: typeof import('./components/ui/slider/Slider.vue')['default']
    SnippetPreview: typeof import('./components/SnippetPreview.vue')['default']
    WithNavbar: typeof import('./components/WithNavbar.vue')['default']
  }
}
